# numpy

In [4]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


## operation

### reshaping 2 X 3 => 3 X 2

In [9]:
reshaping_arr = arr.reshape(1,6)
print(reshaping_arr)

[[1 2 3 4 5 6]]


## data type

In [13]:
## complex
arr3 = np.array([3 + 5j])
print(arr3 , arr3.dtype)
arr4 = np.array([2 + 4j])
print(arr3 +arr4)

[3.+5.j] complex128
[5.+9.j]


## multi-dimention array

In [14]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3d array

In [17]:
arr5 = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr5)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## broadcastion 

In [18]:
arrx = np.array([1,2,3,4,5])
arry = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arrx + arry)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


## aggregation function